### ISSUE TITLE
Could not find suitable distribution for Requirement.parse('pyhal')

### ISSUE THREAD

**Issue by EmptySoft** [sirfoga/pygce#1]
Hi.!

I try to install pygce.  After running **python3 setup.py install --force ** i got following Error

`Installed /usr/lib/python3.4/site-packages/pygce-0.1.2-py3.4.egg
Processing dependencies for pygce==0.1.2
Searching for pyhal
Reading https://pypi.python.org/simple/pyhal/
No local packages or download links found for pyhal
error: Could not find suitable distribution for Requirement.parse('pyhal')`

System: openSUSE Leap 42.2

BYe
    Harald

**Comment by sirfoga** [comment]
The `pypi` package `pyhal` is outdated (as long as the new pypi website is not ready, I cannot update the package), so you should install `pyhal` before installing `pygce` with the following commands:

```shell
$ git clone https://github.com/sirfoga/pyhal && cd pyhal
$ python3 setup.py install
```

**Comment by EmptySoft** [comment]
Thanks for your replay. But if i try to install pyhal i got the Error
`statsmodels/nonparametric/linbin.c:4:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden
 #include "Python.h"
`
I dont know, where i can find Python.h

System now: openSUSE Leap 42.3

**Comment by sirfoga** [comment]
This is a problem of the `statsmodels` installation: it cannot find a necessary header, but it needs to be present in system. Usually it's because you are missing `python3-dev` (or `python-dev`) packages. See also [this stackoverflow answer](https://stackoverflow.com/a/21530768/7643222). Also `pyhal`build is successful according to [travis](https://travis-ci.org/sirfoga/pyhal), see the [config file](https://github.com/sirfoga/pyhal/blob/master/.travis.yml) for details.

**Comment by EmptySoft** [comment]
Hi Stefano.!

Thanks for your really fast replay. I have installed python-dev and the file Python.h is present. Perhaps it is in the wrong Path. I will try to remove all python packages and reinstall them.

Sorry for my noob in Python

**Comment by sirfoga** [comment]
Try with `apt install python3-dev`.
`statsmodel` has to be compiled with `python 3` version, so installing `python-dev` is not enough.

**Comment by EmptySoft** [comment]
Sorry for the late answer. I have crashed my Laptop :(

Your Tip solves my Problem withe the Python.h file. Now i have another problem during setup pyhal. 

`Installed /usr/lib/python3.4/site-packages/PyHal-4.6.3-py3.4.egg
Processing dependencies for PyHal==4.6.3
Searching for scipy
Reading https://pypi.python.org/simple/scipy/
Best match: scipy 0.19.1
Downloading https://pypi.python.org/packages/52/67/d9ef9b5058d4a9e3f0ae641ec151790622cbeb37f157de5773358e2bf3da/scipy-0.19.1.tar.gz#md5=6b4d91b62f1926282b127194a06b72b3
Processing scipy-0.19.1.tar.gz
Writing /tmp/easy_install-4cphfsps/scipy-0.19.1/setup.cfg
Running scipy-0.19.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-4cphfsps/scipy-0.19.1/egg-dist-tmp-3tc8qmh_
/tmp/easy_install-4cphfsps/scipy-0.19.1/setup.py:323: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  warnings.warn("Unrecognized setuptools command, proceeding with "
/usr/lib64/python3.4/site-packages/numpy/distutils/system_info.py:572: UserWarning: 
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  self.calc_info()
/usr/lib64/python3.4/site-packages/numpy/distutils/system_info.py:572: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  self.calc_info()
/usr/lib64/python3.4/site-packages/numpy/distutils/system_info.py:572: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  self.calc_info()
Running from scipy source directory.
non-existing path in 'scipy/integrate': 'quadpack.h'
Warning: Can't read registry to find the necessary compiler setting
Make sure that Python modules winreg, win32api or win32con are installed.
error: no lapack/blas resources found
`

runs pyhal only on Windows?

**Comment by sirfoga** [comment]
`pyhal` has been tested successfully on Ubuntu 16.04. Maybe
```
Make sure that Python modules winreg, win32api or win32con are installed.
```
is a hint to what packages to install, i.e `winreg` `win32api` or `win32con`. Note that this error comes up while installing `scipy`: you can remove the dependency in the [setup file](https://github.com/sirfoga/pyhal/blob/master/setup.py#L72) and continue installation. However you won't be able to run modules depending on `scipy`.

**Comment by sirfoga** [comment]
closed for inactivity
