### ISSUE TITLE
Pygce crashes with "No such file or directory" error

### ISSUE THREAD

**Issue by jakkarth** [sirfoga/pygce#14]
## Expected Behavior

pygce should run and produce an output file, or a reasonable error should be shown so the user can take corrective action.

## Actual Behavior

Program crashes with backtrace and error. No indication is provided as to what directory is missing or why the application expects it to be there, nor what the user can do to fix it.

## Steps to Reproduce the Problem

  1.pygce -user (redacted email address) -c /path/to//Downloads/chromedriver/chromedriver -o foo.json -d 2019-07-01 -p (redacted password)
  1. Observe crash output:

> Traceback (most recent call last):
>   File "/usr/local/bin/pygce", line 9, in <module>
>     load_entry_point('pygce==2.1.2', 'console_scripts', 'pygce')()
>   File "/usr/local/lib/python3.5/dist-packages/pygce-2.1.2-py3.5.egg/pygce/cli.py", line 124, in main
>   File "/usr/local/lib/python3.5/dist-packages/pygce-2.1.2-py3.5.egg/pygce/cli.py", line 115, in check_args
>   File "/usr/lib/python3.5/os.py", line 241, in makedirs
>     mkdir(name, mode)
>  FileNotFoundError: [Errno 2] No such file or directory: ''

## Specifications

  - pygce version (check `pip3 show pygce`): 2.1.2
  - Platform (e.g `Windows 8`, `Mac OSX Sierra`, `Ubuntu 18.04` ...): ubuntu 16.04
  - Url of connection (e.g `https://connect.garmin.com`, if you don't know it,
  then it's the stock one: `https://connect.garmin.com`): default
  - Python version (check `python --version`):  2.7.12/3.5.2

**Comment by jakkarth** [comment]
This issue is not resolved. The new version of the code outputs the following line:

> Trying to create output folder in  ...

And then it crashes with the same backtrace. There's also still no indication of what the user should do to fix the situation when it occurs.

**Comment by sirfoga** [comment]
see d3953774e4fb0a655664e429bfad612932c6efb6 : I took into account your situation

**Comment by jakkarth** [comment]
Ok, based on that code it looks like you're going to try to create the directory for the output file if it doesn't exist. That's not what I was expecting. If the directory didn't exist, I expected an error saying the directory doesn't exist, like most programs do. Your fix makes sense since I wasn't specifying a path for my output file. I will try this out and report back.

**Comment by jakkarth** [comment]
That seems to have resolved this particular problem. Thanks.
