### ISSUE TITLE
Daily summary content failing to load

### ISSUE THREAD

**Issue by FelixHarvey** [sirfoga/pygce#16]
## Expected Behavior

Daily summary content successfully loads in chromedriver and is able to be scraped.

## Actual Behavior

Daily summary content does not load (menu bars do), as shown in screenshot below. This page will load in a normal browsing tab (ie this same URL has been copied across to a normal chrome window and loads instantly).

Note that the timeout length has been extended to 60s and the same issue still occurs.

<img width="1198" alt="Screen Shot 2020-06-23 at 2 37 43 pm" src="https://user-images.githubusercontent.com/8462475/85361620-c469a580-b55f-11ea-8738-5853de02209b.png">

## Steps to Reproduce the Problem

  1. Install pygce
  2. Run with single date.
 3. Wait for page to not load.

## Specifications

  - pygce version (check `pip3 show pygce`):
Version: 2.1.2

  - Platform (e.g `Windows 8`, `Mac OSX Sierra`, `Ubuntu 18.04` ...):
macOS Catalina (10.15.4)

  - Url of connection (e.g `https://connect.garmin.com`, if you don't know it,
  then it's the stock one: `https://connect.garmin.com`):
"https://connect.garmin.com"

  - Python version (check `python --version`):
Python 3.8.3

**Comment by sirfoga** [comment]
Dear @FelixHarvey ,

thanks. Garmin just updated its front-end and pygce relies just on that to see if the page has been loaded correctly. 41f35aa22d6a522066b96a47162660070e6e983e hopefully solves your issue. Give it a try and let me know.

**Comment by FelixHarvey** [comment]
@sirfoga thank you very much! 

That has fixed the problem outlined above. However, along with the front-end update it seems that the way in which the daily data is displayed has changed. When I run the script, in the output JSON file, activities, breakdown, sleep, steps & summary all are blank or None. I assume (and think from a quick look) this is because the html tags have changed with the UI update.

Let me know if I should open a new issue or can be of any assistance in fixing this.

**Comment by sirfoga** [comment]
@FelixHarvey yes indeed. If you want to contribute with the fixed tags please do so. Open a pull request. Thanks
