### ISSUE TITLE
'WebDriver' object has no attribute 'fill_form_field'

### ISSUE THREAD

**Issue by suttondaniel** [sirfoga/pygce#17]
## Expected Behavior
Scrape data from Garmin Connect. 

## Actual Behavior
It gets stuck on the login screen.  The exact error is as follows: 

```
2020-07-29 20:52:29,376 - pygce - **ERROR - 'WebDriver' object has no attribute 'fill_form_field'**
2020-07-29 20:52:29,376 - pygce - DEBUG - GET https://connect.garmin.com/modern/
2020-07-29 20:52:32,031 - pygce - DEBUG - attempt 0
```

So it looks as though it has something to do with the pyhal package?    I was getting a different error before, but changed the imports to: 

`from hal.internet.selenium.forms import SeleniumFormFiller`

which fixed that issue.  And now I am getting the issue that 'WebDriver' object has no attribute 'fill_form_field'.  

## Steps to Reproduce the Problem

  1.  pygce -user redacted@gmail.com -p redacted -c /c/Users/name/documents/folder/fitness/scrapesteps/chromedriver.exe -d 2018-09-05 2020-07-28 -o /c/Users/name/documents/folder/fitness/scrapesteps -f json

## Specifications

  - pygce version (check `pip3 show pygce`):      **1.9.8**
  - Platform (e.g `Windows 8`, `Mac OSX Sierra`, `Ubuntu 18.04` ...):     **Windows 10**
  - Url of connection (e.g `https://connect.garmin.com`, if you don't know it,
  then it's the stock one: `https://connect.garmin.com`):      **Default connection.**  
  - Python version (check `python --version`):        **3.8.3**

**Comment by sirfoga** [comment]
@suttondaniel update to latest version (2.2.0, `pip install -U .` from the fresh-cloned local repository) and let me know

**Comment by suttondaniel** [comment]
`$ pygce -user redacted@gmail.com -password password123 -c /c/Users/name/documents/folder/fitness/scrapesteps/chromedriver.exe -d 2018-09-05 2020-07-28 -out /c/Users/name/documents/folder/fitness/scrapesteps/testing
2020-07-30 14:39:49,924 - pygce - DEBUG - Region: garmin.com
`

I did a fresh install with the latest version, and am now running into trouble keeping the webdriver open.  

The selenium window opens then closes pretty much immediately.  Let me know thoughts!  Thanks.  @sirfoga

**Comment by sirfoga** [comment]
Any debug trace? I have never tested it under Windows. Is your chromedriver updated?

**Comment by suttondaniel** [comment]
No debug trace....and the chromedriver is up to date, and was working before I updated the package.

**Comment by sirfoga** [comment]
Please run it with a proper output file: I use your output file `/c/Users/name/documents/folder/fitness/scrapesteps/testing` to parse the format so

- if you want json format use `/c/Users/name/documents/folder/fitness/scrapesteps/testing.json`
- if you want csv format use `/c/Users/name/documents/folder/fitness/scrapesteps/testing.csv`

**Comment by suttondaniel** [comment]
Thanks @sirfoga, that fixed the webdriver issue.
