### ISSUE TITLE
Can i save gpx files from garmin connect, too?!?

### ISSUE THREAD

**Issue by jedie** [sirfoga/pygce#2]
Only a question: Can i save gpx files from garmin connect, too?!?

**Comment by sirfoga** [comment]
@jedie just run with `-gpx "yes"` and you can find your `.gpx` in your downloads folder

**Comment by sirfoga** [comment]
I know it's kinda messy, but you need to have a GarminConnect-validated cookie in order to download the .gpx files. If you have Strava, you can import your activities there and download the .gpx with https://github.com/albymor/StravaGpxDownloader

**Comment by jedie** [comment]
I used https://github.com/pe-st/garmin-connect-export to download the gpx files.
I think it makes sense to work together.
