### ISSUE TITLE
'NoneType' object has no attribute 'date'

### ISSUE THREAD

**Issue by eastabrooka** [sirfoga/pygce#4]
Hi, 
So 1st, I wanted to say a Massive Thankyou. 
I've been pestering the Garmin people for API and they turn you away saying - Pay the Money, or Jog on!

So - I have got Virtualbox, and installed Ubuntu LTS 18.04.1.

I have got Python 3.6 on Ubuntu - This satisfies some of the min installation critera of Numpy, 
https://stackoverflow.com/questions/42662104/how-to-install-pip-for-python-3-6-on-ubuntu-16-10

Anyway - I have run the Setup for pygce as you have suggested in your detailed Readme. 
I have given the correct parameters, to the pygce application. 

It starts Chromium in Automation mode.  It logs in successfully as me. 
It goes to "https://connect.garmin.com/modern/" and then stops with the following exception. 

Getting day 2018-10-02 00:00:00
Getting user dashboard from https://connect.garmin.com/modern/
Message:
Traceback (most recent call last):
  File "/usr/local/bin/pygce", line 11, in <module>
    load_entry_point('pygce==1.9.8', 'console_scripts', 'pygce')()
  File "/home/eastabrooka/.local/lib/python3.6/site-packages/pygce/cli.py", line 133, in main
    bot.save_json_days(days[0], days[1], path_out)
  File "/home/eastabrooka/.local/lib/python3.6/site-packages/pygce/models/bot.py", line 227, in save_json_days
    print("Parsing day", str(d.date))
AttributeError: 'NoneType' object has no attribute 'date'

## Expected Behavior
The pygce to pull the daily-summary for yesterday

## Actual Behavior
Exception. 

## Steps to Reproduce the Problem
  1. pygce -user user@account.com -p password -c /home/eastabrooka/Downloads/chromedriver -d 2018-10-02 -f json -o ./output.txt
  1.exception occurs. 

## Specifications

  - pygce version (check `pip3 show pygce`):
Name: pygce
Version: 1.9.8
Summary: pygce is an unofficial Garmin Connect data exporter.
Home-page: https://github.com/sirfoga/pygce
Author: sirfoga
Author-email: sirfoga@protonmail.com
License: UNKNOWN
Location: /home/eastabrooka/.local/lib/python3.6/site-packages
Requires: bs4, pyhal, lxml, numpy, sklearn

  - Platform (e.g `Windows 8`, `Mac OSX Sierra`, `Ubuntu 18.04` ...):
Ubuntu LTS 18.04.1.

  - Url of connection (e.g `https://connect.garmin.com`):
Stock - Whatever Pygce uses as default 

  - Python version (check `python --version`):

eastabrooka@GarminScraper:~/pygce$ python3 --version
Python 3.6.6

Thank you again for posting Pygce, its very useful !

**Comment by eastabrooka** [comment]
So - One thing I have noticed is when I go to my  daily-summary page, it isnt using the (self.user_id) that _find_user_id will parse. It is using 
https://connect.garmin.com/modern/daily-summary/Eastabrooka/2018-10-03/timeline
When I try and go to 
https://connect.garmin.com/modern/daily-summary/USER ID/2018-10-03/timeline
it says "You don't have permission to see this"

I have done a small mod to this function to force it to return  self.user_id = "Eastabrooka"

I can see in Chromium the Daily-Summary now being loaded correctly. It still fails to parse the day / days. 

I will upload a detailed log next.

**Comment by sirfoga** [comment]
The `user_id` thing is not a problem, whereas the `'NoneType' object has no attribute 'date'` is actually a bug caused by the Garmin website too slow to load in time.
One workaround (that you actually performed) is to set a larger timeout, but this does not scale.
On the other hand now (since e261727618b6c395d106eb2d5fc5a49b675bc25b) I grab `user_id` in a different way: I parse the top bar (that is loaded before anything else at the bottom).

The issue should be resolved, but please try it! Thank you again for testing this out.

**Comment by eastabrooka** [comment]
Hi Sirfoga, 

Thanks again for looking into this, but I think I still have the issue. 
I have screen-capped the process I have taken, in checking out the update you have pushed, and the error that I encounter. 
I have uploaded it here. https://www.youtube.com/watch?v=wkGiytDYWVg

I hope this helps. I don't fully know why Garmin would give some users a ID and some users a Name in the URL Bar. 

( I just wish they had just given us an API ! ) 
Thanks Again

**Comment by sirfoga** [comment]
Thanks, so it is actually the `used_id` the problem ;(
Go to your dashboard, view the source of the top right icon

**Comment by sirfoga** [comment]
@eastabrooka 
Thanks, so it is actually the `used_id` the problem ;(
Go to your dashboard, view the source of the top right icon

For instance:
![screenshot from 2018-10-06 15-04-50](https://user-images.githubusercontent.com/14162628/46572113-d1f08d80-c980-11e8-808d-79ec17025227.png)

**Comment by sirfoga** [comment]
Anyway, if you just want the activities (and not the daily summary), you can also use [this](https://github.com/pe-st/garmin-connect-export) unofficial Garmin Connect exporter

**Comment by eastabrooka** [comment]
Hi, 
![image](https://user-images.githubusercontent.com/11888681/46572218-d49bb480-c979-11e8-871d-8d08c2f81dac.png)
Here is the requested Source from the dashboard. 

To be honest, Its the Steps that are my main interest. 
In my fork, I have it working for me ( But by hacky hardcoded patch )
Primary use was I wanted to tie the Steps into some Home Automation stuff.  i.e. If Not 10000 Steps, Do X, Y etc. 

But I am still very interested in getting the ability to dump out all the data ive ever given Garmin to make a dataset for analysis :). 

Thanks again for your help.

**Comment by sirfoga** [comment]
I've watched your youtube video one more time, are you sure it's the latest version? What commit are you in? Have you forced the re-installation? My outputs are a little different:

![u](https://user-images.githubusercontent.com/14162628/46572805-1e8d9600-c98c-11e8-90c6-2ab3fa1b00e0.png)

I've just added a version checker to be sure. Please, run `$ pip3 install . --upgrade --force-reinstall` from the source. The output version should be `>= 1.9.8`, for instance running `pip3 show pygce` shows:
```
Name: pygce
Version: 1.9.8
Summary: pygce is an unofficial Garmin Connect data exporter.
Home-page: https://github.com/sirfoga/pygce
Author: sirfoga
Author-email: sirfoga@protonmail.com
License: UNKNOWN
Location: /usr/local/lib/python3.6/dist-packages
Requires: lxml, numpy, sklearn, pyhal, bs4
Required-by:
```

**Comment by eastabrooka** [comment]
Hi,
Sorry to drop the cadence on the replies. Its been busy. Thank you again for looking into this. 

1 ) I was running the old Pygce. I missed the force reinstall. 
2 ) Its getting closer ! It does load the correct page now, But it still delivers the out of range problem. 
3 ) https://www.youtube.com/watch?v=lcBSQZqz98M&feature=youtu.be
4 ) https://pastebin.com/KfhxFzX1
5 ) I did run pip3 show pygce - and it now says 1.9.8

I also thought to give you the raw HTML from what is on 'My' page..
I do think that it may be that as with our User IDs being different, the HTML vended may also be different. [RawHTMLGarminDump.txt](https://github.com/sirfoga/pygce/files/2466495/RawHTMLGarminDump.txt)

**Comment by sirfoga** [comment]
Thank you again for your detailed report.

It seems that while I have a `Breakdown` section, you don't (which seems strange, since I have a Forerunner 235, while your watch is a lot better :sweat_smile:)

Anyway, I added a `try-except` block in all `parse` methods. I've tried it with your source page and it works fine (it doesn't log the `Breakdown` section, but at least it exits without errors :innocent:)

**Comment by eastabrooka** [comment]
Ahh Garmin. Non-Uniform-ness.. 
So - I have updated to your change set and rebuit, reinstalled. 

Problem 1 ) - Is it doesn't enter the Username and Password in the first hurdle anymore. 
So - As shown by the comment I made  https://github.com/sirfoga/pygce/commit/2099c0ba45e7260c9df274f66fe7783f1cabbc3b 
I reverted this change on my local check out, rebuilt... 

And now ! 
![image](https://user-images.githubusercontent.com/11888681/46853844-2ff4f900-cdf7-11e8-9b89-9294ba0cb2be.png)

It correctly parses and dumps to file !

**Comment by sirfoga** [comment]
Oops, really my bad here. The thing is I'm working on my other repo and I just did *not* release the latest version (so that I can use `SeleniumForm(self.browser).fill_login_form(...)` instead of `SeleniumForm.fill_login_form(...)`).

Now, running `pip3 install . --upgrade --force-reinstall` will install the latest library version and there should not be any more problems :sweat_smile:
