### ISSUE TITLE
No module named 'hal.internet.selenium_bots'

### ISSUE THREAD

**Issue by b-paredes** [sirfoga/pygce#7]
## Expected Behavior
"pygce -h" returns a help screen

## Actual Behavior
"pygce -h" returns the following:

**ModuleNotFoundError: No module named 'hal.internet.selenium_bots'**

Traceback (most recent call last):
  File "/Users/paredes/venv.pygce/bin/pygce", line 7, in <module>
    from pygce.cli import main
  File "/Users/paredes/venv.pygce/lib/python3.7/site-packages/pygce/cli.py", line 9, in <module>
    from pygce.models.bot import GarminConnectBot
  File "/Users/paredes/venv.pygce/lib/python3.7/site-packages/pygce/models/bot.py", line 10, in <module>
    from hal.internet.selenium_bots import SeleniumForm
ModuleNotFoundError: No module named 'hal.internet.selenium_bots'
(venv.pygce) 

## Steps to Solve the Problem
  1. Reinstalled Python
  1. Reinstalled Selenium
  1. Reinstalled chromedriver
  1. Reinstalled pygce

## Specifications

  - pygce version (check `pip3 show pygce`):
1.9.8
  - Platform (e.g `Windows 8`, `Mac OSX Sierra`, `Ubuntu 18.04` ...):
Mac OSX High Sierra ver 10.13.6
  - Url of connection (e.g `https://connect.garmin.com`, if you don't know it,
  then it's the stock one: `https://connect.garmin.com`):
Https://connect.garmin.com/en-US/signin
  - Python version (check `python --version`):
Python 3.7.0
  -Selenium ver 3.141.0;  urllib3 ver 1.24.1

**Comment by sirfoga** [comment]
Please @b-paredes make sure you have the latest version installed. The latest version is the [2.0.6](https://github.com/sirfoga/pygce/blob/master/VERSION). Moreover this bug has been fixed in #6 .
